version: '3'
services: 
    frontend:
        build: 
            context: './frontend'
            dockerfile: 'Dockerfile'
        volumes: 
            - /frontend/node_modules
            - ./frontend:/frontend
        ports:
            - "${WEB_CLIENT_PORT}:3000"
        restart: on-failure
        container_name: domotyx-hub-frontend
    backend:
        build:
            context: './backend'
            dockerfile: 'Dockerfile'
        volumes: 
            - /backend/node_modules
            - ./backend:/backend
        ports:
            - "${REST_API_PORT}:${REST_API_PORT}"
        restart: on-failure
        container_name: domotyx-hub-backend
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_HOST=${MONGO_INITDB_HOST}
            - MONGO_INITDB_PORT=${MONGO_INITDB_PORT}
            - REST_API_PORT=${REST_API_PORT}
            - WEB_CLIENT_PORT=${WEB_CLIENT_PORT}
    database:
        image: mongo:latest
        env_file: 
            - .env
        ports:
            - "${MONGO_INITDB_PORT}:27017"
        container_name: domotyx-hub-database